### ISSUE TITLE
Funday event is broken

### ISSUE THREAD

**Issue by TheFrenchGhosty** [PussTheCat-org/PussTheCat.org-Cod4x-KTK#11]
If what I read in the event gsc is correct, the funday event is supposed to set the map to lolzor and nothing more.

However, it doesn't do that, and the voted map just go on.

If I set it with the command the event just restart the current map.

It's not a big problem for the server since lolzor is in rotation, so maybe just removing the event is the way to go.

**Comment by VikingKampfsau** [comment]
Funday is "normal" KtK with some custom settings, not really an event.
The Ninja guys used it to activate 3x XP and a map rotation with small maps.

Basically a big mess with fast rounds, a lot of rage but a nice reward of XP to rank up.
