### ISSUE TITLE
lolzor spawn protection can be bypassed with 10 fps

### ISSUE THREAD

**Issue by TheFrenchGhosty** [PussTheCat-org/PussTheCat.org-Cod4x-KTK#12]
The lolzor spawn protection can be bypassed with 10 fps, consistently, the protection should either be "stronger" or maybe, a more simple way, add the promod screen that ask to set the fps to 125-333

**Comment by TheFrenchGhosty** [comment]
The fix takes too long to trigger (between 1 and 3 seconds) and players are still able to go through.

**Comment by VikingKampfsau** [comment]
I am afraid but i think there is nothing we can do then.
