### ISSUE TITLE
Hide and Seek: Changing the event to none and fast_restart crash the server

### ISSUE THREAD

**Issue by TheFrenchGhosty** [PussTheCat-org/PussTheCat.org-Cod4x-KTK#14]
If the server is currently running the hide and seek event, and an admin decide to change the event to none, and then fast_restart: the server will just crash.

**Comment by VikingKampfsau** [comment]
You can not use fast_restart in this case because that will mix the settings of two gametypes and might result in an overflow on the client side.

Either play the round and wait for the game to change the event to none, or use map_restart.

**Comment by TheFrenchGhosty** [comment]
>that will mix the settings of two gametypes

I guess that's what's crashing the server.

Good to know!
