### ISSUE TITLE
Throwing knife is too slow

### ISSUE THREAD

**Issue by TheFrenchGhosty** [PussTheCat-org/PussTheCat.org-Cod4x-KTK#15]
Some player asked if there was a way to speed up the animation to throw it because they feel like it's too slow.

I agree, but I'm wondering if it's possible or not since it's basically just a "grenade".

**Comment by VikingKampfsau** [comment]
Remove the images (*.iwi) of the skins from thw following iwds:
z_ktk1.iwd
z_ktk2.iwd
z_ktk3.iwd

I have no idea which exactly because this 3 files contain the skins and textures the ninja guys applied.
You can also remove this 3 files completely to fall back to CoD4 default textures.

**Comment by VikingKampfsau** [comment]
I tweaked the timers a bit but from what i heard it's still too slow.

Right now the knife is at:
fireTime\0.9\holdFireTime\0.06\

The frag grenade (which is the fastest in CoD4):
fireTime\0.36\holdFireTime\0.6\

holdFireTime = Time to pull the pin and "move the hand behind the body"
fireTime = Time to throw it after the pin is pulled

As you can see the pullpin is pretty fast but the throwing itself is not.
I will make some tests and see how much i can tweak the timers before it breaks the anims.

**Comment by TheFrenchGhosty** [comment]
Done in update 6.
