### ISSUE TITLE
Multiples concrete textures are replaced by a grass texture

### ISSUE THREAD

**Issue by TheFrenchGhosty** [PussTheCat-org/PussTheCat.org-Cod4x-KTK#16]
The texture ch_asphalt01, a ground texture, is replaced by a grass texture, this cause different issues in map using it, like for example in mp_bo2meltdown2 where it's used on a road:

![aaa](https://user-images.githubusercontent.com/47571719/114384915-dbc16000-9b7e-11eb-92c1-11ad72071a1d.png)

**Comment by VikingKampfsau** [comment]
Remove the images (*.iwi) of the skins from thw following iwds:
z_ktk1.iwd
z_ktk2.iwd
z_ktk3.iwd

I have no idea which exactly because this 3 files contain the skins and textures the ninja guys applied.
You can also remove this 3 files completely to fall back to CoD4 default textures.

**Comment by TheFrenchGhosty** [comment]
Fixed by removing ch_asphalt01_col.iwi from z_ktk2.iwd.

![aaa](https://user-images.githubusercontent.com/47571719/114388998-f77b3500-9b83-11eb-9146-f78349c34cf7.png)

**Comment by TheFrenchGhosty** [comment]
It was also a problem for me_asphalt_01.iwi and me_asphalt_road1_color.iwi

**Comment by TheFrenchGhosty** [comment]
7 more textures had this problem, this is now fixed:

ch_ground_dirt02_col.iwi
ch_ground_mud03_col.iwi
ch_rubble01_col.iwi
me_grass_dry_col.iwi
me_ground_sand02_col.iwi
me_ground_sand03_col.iwi
me_stone_road01_col.iwi
