### ISSUE TITLE
Add a control for fov_scale in the UI

### ISSUE THREAD

**Issue by TheFrenchGhosty** [PussTheCat-org/PussTheCat.org-Cod4x-KTK#17]
Players requested a way to change the fov_scale from the UI.

**Comment by VikingKampfsau** [comment]
Already in the mod, right under the fov setting in player menu.
![grafik](https://user-images.githubusercontent.com/82271312/114544140-82c6fa00-9c5a-11eb-947d-b51a633ab553.png)

The name might be a bit confusing, i'll change that with the next update.

**Comment by TheFrenchGhosty** [comment]
Mmh in English it's named Depth of Field, so yeah it's not the right name.
