### ISSUE TITLE
Allow setting the Assassins bots skill separately than the Guardians bots skill

### ISSUE THREAD

**Issue by TheFrenchGhosty** [PussTheCat-org/PussTheCat.org-Cod4x-KTK#22]
Assassins bot aren't good enough compared to the Guardians bots.

Ideally, they should have separate skill value (like what you added for the king) that I can change, so that I can set the assassins stronger than the guardians.

**Comment by VikingKampfsau** [comment]
Added, now we have:
`	setDvar("scr_ktk_bots_skillAssAssins", "0.6");		//0-1 -> 0 = they don't attack; default = 0.4
	setDvar("scr_ktk_bots_skillGuards", "0.6");			//0-1 -> 0 = they don't attack; default = 0.4
	setDvar("scr_ktk_bots_skillKing", "0.6");			//0-1 -> 0 = he doesn't attack; default = 0.4`
