### ISSUE TITLE
Add the M40A3 to the assassins weapon rotation

### ISSUE THREAD

**Issue by TheFrenchGhosty** [PussTheCat-org/PussTheCat.org-Cod4x-KTK#23]
Viking answer:

>not possible - the m40a3 was replaced with the intervention

Isn't it possible to make the intervention replace another (useless) weapon, like the Barret?

In my opinion the M40A3 is a useful weapon to have in the assassins rotation.

**Comment by VikingKampfsau** [comment]
I'll check if we can implement it the way it's done with the knife.
The animations should be the same as the r700, so we might be able to put it together in a single weapon file.
They will share the damage and stuff, but i think that's fine.

**Comment by TheFrenchGhosty** [comment]
The thing is that the M40A3 animation is slower, so it might be a problem.

**Comment by TheFrenchGhosty** [comment]
Done in update 6.
