### ISSUE TITLE
"Join last server" on the main menu doesn't work.

### ISSUE THREAD

**Issue by TheFrenchGhosty** [PussTheCat-org/PussTheCat.org-Cod4x-KTK#24]
I asked on Discord:

>"Join last server" on the main menu should just be a /reconnect

Viking answer:

> not a good idea because /reconnect only works when you did not close the game.
>the current button allows to reconnect even when the game was closed (requires a non writeprotected config on the client side)

My answer:

>The problem is that the IP is enforced though

Viking answer:

>nope.

>menu:

>`CHOICE_BUTTON_VIS( 4, "Join last server", exec "vstr connectlastserver";, when(dvarString(connectlastserver) !=  ""))`

>gsc:

>`self setClientDvar("connectlastserver", "connect " + getDvar("net_ip") + ":" + getDvar("net_port"));`

>getDvar() is grabbing the server dvar

---

Problem: this doesn't work.

**Comment by VikingKampfsau** [comment]
You don't have set net_ip in the startup script or in your config.
Add it and the button should work for reconnectiong to your server.
(when the player config is not write protected and allows to write that setting)

![grafik](https://user-images.githubusercontent.com/82271312/114677212-608cb500-9d0a-11eb-9408-037357c89880.png)
