### ISSUE TITLE
Server should automatically switch to a map with bots if there's no player connected

### ISSUE THREAD

**Issue by TheFrenchGhosty** [PussTheCat-org/PussTheCat.org-Cod4x-KTK#26]
Currently the server will run for a while with bots, since if no one votes the event/map will be selected randomly.

However there's a problem:

If the server switch to a map without bot, it will just stay there, problem: if one player connect, he won't be able to play a map with bots unless another player connect.

In my opinion the server, when no players are connected should just be running bots maps: if it runs a map, and no one is there to play: it just switch to another map, either a specific map (mp_nuketown ideally) or a random map.

**Comment by VikingKampfsau** [comment]
In config/server/gameplay.gsc you have a setting which controls how long the server can stay empty before it rotates to a random map.

setDvar("scr_mod_empty_time", "15"); // time in minutes...

I modified the script behind it to check if there are maps with bots in the rotation.
If so it picks a random map with bots, if not then it picks any random map.

Please keep an eye on that and close this report when it works.

**Comment by TheFrenchGhosty** [comment]
@VikingKampfsau Seems to work, however, it sometimes switch to an event that don't support bots, and will just stay there.

In my opinion it should only go on the event:none.

**Comment by VikingKampfsau** [comment]
Event reset to "none" added before it switchs map.
