### ISSUE TITLE
Killstreaks Display with Lagometer

### ISSUE THREAD

**Issue by VikingKampfsau** [PussTheCat-org/PussTheCat.org-Cod4x-KTK#31]
The lagometer is on top of the killstreaks.
To fix it I have to change their position in hud.menu when the lagometer is enabled

**Comment by TheFrenchGhosty** [comment]
Screenshot for context:

![aaeae](https://user-images.githubusercontent.com/47571719/114750265-53d88300-9d43-11eb-96c4-0530c9a6c091.png)

**Comment by VikingKampfsau** [comment]
Fixed:

With Lagometer disabled:
![grafik](https://user-images.githubusercontent.com/82271312/114857784-f72fa380-9de8-11eb-9318-fbc675c2d991.png)


With Lagometer enabled:
![grafik](https://user-images.githubusercontent.com/82271312/114857899-19c1bc80-9de9-11eb-81df-78e8c13bd853.png)
