### ISSUE TITLE
Dogfight event: joining_team is undefined

### ISSUE THREAD

**Issue by TheFrenchGhosty** [PussTheCat-org/PussTheCat.org-Cod4x-KTK#33]
![dog_-_joining_team_bug](https://user-images.githubusercontent.com/47571719/114750378-74a0d880-9d43-11eb-95f4-867881a75c07.png)

**Comment by VikingKampfsau** [comment]
I can not remember why this debug message was added in 2018.
Did you notice anything wrong?

**Comment by TheFrenchGhosty** [comment]
Nope, everything seems to be working.

**Comment by TheFrenchGhosty** [comment]
Fixed in update 6.
