### ISSUE TITLE
"Last update" has no value in the loading screen

### ISSUE THREAD

**Issue by TheFrenchGhosty** [PussTheCat-org/PussTheCat.org-Cod4x-KTK#35]
![mod_version_top_right](https://user-images.githubusercontent.com/47571719/114750790-e547f500-9d43-11eb-93b8-39a569eb61ec.png)

As I recommended on Discord, just removing everything that's on top right is the way to go in my opinion.

**Comment by VikingKampfsau** [comment]
Removed the date from the loadscreen

![Uploading grafik.png…]()
