### ISSUE TITLE
FOV scale doesn't go high enough

### ISSUE THREAD

**Issue by TheFrenchGhosty** [PussTheCat-org/PussTheCat.org-Cod4x-KTK#36]
Follow up to #17

Some people ask for it to go higher.

For example, in another server, this is the available options for it:

![aaaa](https://user-images.githubusercontent.com/47571719/114751339-90f14500-9d44-11eb-895a-b422344c7aa0.png)

And I was told by someone that they use 1.40

**Comment by VikingKampfsau** [comment]
Changed.

Settings are now:
1
1.125
1.25
1.375
1.5
