### ISSUE TITLE
Bots sometimes stop into things or glitch through them

### ISSUE THREAD

**Issue by TheFrenchGhosty** [PussTheCat-org/PussTheCat.org-Cod4x-KTK#37]
For whatever reason, on a lots of maps, because of - I'm guessing bad waypoints files - the bots will get stuck to stuff, and sometimes, they will just glitch through them and get teleported to the other side.

The biggest issue is when they stop in front of something, in my opinion they should just try another way if they can't go there, and obviously, they shouldn't glitch through them.

**Comment by VikingKampfsau** [comment]
Fix the waypoints, this is not pezbots where bots are linked to an invisible object and move through whatever is in their way.

**Comment by VikingKampfsau** [comment]
Added a weapon box that has no collision - this will fix the stuck bots at the bomb spots of the maps which are used to buy weapons in ktk.

However, when they get stuck in buildings, props, walls, doors or anything else then it's a problem of the waypoints.
