### ISSUE TITLE
mp_bubba break some scripts

### ISSUE THREAD

**Issue by TheFrenchGhosty** [PussTheCat-org/PussTheCat.org-Cod4x-KTK#4]
mp_bubba is broken (and was broken on the previous version of the mod): it break the script that make people join the king, making everyone, including assassin's and slave join the king team.

![s](https://user-images.githubusercontent.com/47571719/114206729-278bc380-994b-11eb-8f74-0916d7a4108a.png)

**Comment by TheFrenchGhosty** [comment]
Viking answer:

>propably a custom script in the map, i will take a look

**Comment by TheFrenchGhosty** [comment]
[mp_bubba.gsc.txt](https://github.com/PussTheCat-org/PussTheCat.org-Cod4x-KTK/files/6286998/mp_bubba.gsc.txt)

[mp_bubba_mip.gsc.txt](https://github.com/PussTheCat-org/PussTheCat.org-Cod4x-KTK/files/6286997/mp_bubba_mip.gsc.txt)

Both scripts extracted from the map.

(I added .txt at the end since Github doesn't like files ending in .gsc)

**Comment by VikingKampfsau** [comment]
None of this can break the team switch of a player.
I'll make some researches.

**Comment by VikingKampfsau** [comment]
Works fine on the development server when there are enough players.
Main assassin, slave/dog do not change team.

Please try it again when some more players are online and report back.

**Comment by TheFrenchGhosty** [comment]
It happens after some time, like after 1-2 rounds.

**Comment by VikingKampfsau** [comment]
Oh, i must be blind.
Not sure if this really could cause problems, but that mapper has a call of a script with a wait 35.
This call has to be threaded.

I'll add it to the next update

**Comment by TheFrenchGhosty** [comment]
Seems fixed in update 6.
