### ISSUE TITLE
Traitors event: Broken with 2 players

### ISSUE THREAD

**Issue by TheFrenchGhosty** [PussTheCat-org/PussTheCat.org-Cod4x-KTK#41]
If only 2 players are connected the event will bug and the rounds will end instantly, with "All innocents killed".

**Comment by VikingKampfsau** [comment]
Ok i understand now.
The thing is that the minimum of players required for this event is 3.
1 King, 1 innocent and 1 traitor.

The mod itself is grabbing the minplayer setting from config where you set 2.
I force the minplayer setting to 3 now when the event is traitors.

Please report back if this solution works (but i guess it does).

**Comment by TheFrenchGhosty** [comment]
Fixed in update 6.
