### ISSUE TITLE
The anti-low fps script is triggered when alt-tabbing

### ISSUE THREAD

**Issue by TheFrenchGhosty** [PussTheCat-org/PussTheCat.org-Cod4x-KTK#42]
Alt-tabbing the game trigger the anti-low fps that was made for lolzor (#12).

It also seem to trigger if the player get a micro-freeze.

2 new enhancements are required:

- It should set the FPS to 125 when triggered
- It should trigger after 1/2 second of low fps

**Comment by VikingKampfsau** [comment]
Nothing i can do. 
The FPS grab is a cod4x build in function and somehow calculates the fps of the player (don't ask me how).
