### ISSUE TITLE
Bots are attracted to weapons boxes

### ISSUE THREAD

**Issue by TheFrenchGhosty** [PussTheCat-org/PussTheCat.org-Cod4x-KTK#45]
Related to #37 

They are, for whatever reason attracted to weapons boxes, they seems to spam the use of it, but since they can't get anything because they don't have the points, they just keep trying.

**Comment by VikingKampfsau** [comment]
Bots don't care about weapon boxes, the problem might be they waypoints.
Waypoints are usually added when the gametype is dm/tdm which has no bomb spots.
Fix the waypoints and the bots will navigate around the boxes and not get stuck there.

**Comment by TheFrenchGhosty** [comment]
Fixed in update 6 since it removed weapon box collision.
