### ISSUE TITLE
VIPs don't have any perks

### ISSUE THREAD

**Issue by TheFrenchGhosty** [PussTheCat-org/PussTheCat.org-Cod4x-KTK#47]
According to what you (Viking) told me on Discord, VIPs are supposed to have:

- RPG
- Self-revive
- More health

However, I'm sure: they don't have RPG, they don't have self-revive, and as king they don't have more health.

Also: I think you should add an icon to the score board to show who's VIP.

**Comment by VikingKampfsau** [comment]
Works fine for me on the development server.
Are you sure you added the correct GUID to the config?

**Comment by TheFrenchGhosty** [comment]
It's the last 8 characters of the guid reported by /myguid ? 

If so, yes, this is what I added.

**Comment by VikingKampfsau** [comment]
Old CoD4 system returns last 8 digits only but the latest CoD4x function returns the full guid.
I added a short check for the guid length now to cut it down to the last 8 digits when the guid has more then 8 digits.

Confirmed as working from TheFrenchGhosty on discord.
