### ISSUE TITLE
Cant reset challenges

### ISSUE THREAD

**Issue by sven-sex** [PussTheCat-org/PussTheCat.org-Cod4x-KTK#49]
Resetting challenges does not work

**Comment by VikingKampfsau** [comment]
Works fine on the test server.

Make sure you have "scr_mod_blockChallengeReset" set to "0" in config.
config/gameplay.gsc

**Comment by sven-sex** [comment]
Hadn't worked on Cheshire's server, so if he hasn't fixed it then it still doesn't work
