### ISSUE TITLE
Event hide and seek crash the server

### ISSUE THREAD

**Issue by TheFrenchGhosty** [PussTheCat-org/PussTheCat.org-Cod4x-KTK#5]
The server will crash when changing to hide and seek.
```
 ]./cod4x18_dedrun: symbol lookup error: /home/cod4x/cod4x-ktk/plugin.xmodellist.tmp: undefined symbol: ARRAY_COUNT
```

**Comment by VikingKampfsau** [comment]
is that happening randomly or always on the same map(s)?

**Comment by TheFrenchGhosty** [comment]
@VikingKampfsau I just edited, it's when the event is set to hide and seek.

**Comment by VikingKampfsau** [comment]
Please try the new plugin and close the issue if it works.

**Comment by TheFrenchGhosty** [comment]
Fixed with the new plugin.
