### ISSUE TITLE
FOV reset at the end of a each map

### ISSUE THREAD

**Issue by TheFrenchGhosty** [PussTheCat-org/PussTheCat.org-Cod4x-KTK#50]
Latest update, I'm guessing the fix for the cg_fov 0 break something, and now the FOV seems to reset at every map.

**Comment by VikingKampfsau** [comment]
Is it resetting at the end of the map or after reconnecting to the new map?
or at end/beginning of a round?

**Comment by TheFrenchGhosty** [comment]
After reconnecting to the new map.

It seems to be working after setting it back to the wanted value in the B5 menu.

**Comment by VikingKampfsau** [comment]
a bit annoying but not really a bug.

KtK Settings are stored in stats but a stat is 0 until it's set for the first time.
The FoV setting is forced to 65 (cod4 default) when the stat is 0.

So for every player the fov changes on he first connection to 65.
After changing it inside the ktk settings menu it will persist.
