### ISSUE TITLE
Disable grenade cooking or disable self damage by it

### ISSUE THREAD

**Issue by TheFrenchGhosty** [PussTheCat-org/PussTheCat.org-Cod4x-KTK#52]
Currently the grenade unlock-able can be cooked: it's a problem because it damage the player who throw it, and, if kept cooked it will just kill the player.

In my opinion grenade should either not be "cookable" or they shouldn't damage the player who "own" it.

Disabling cooking is maybe the more balanced way to handle this issue.

**Comment by VikingKampfsau** [comment]
That's an issue since day one.
I think the only way to fix this is to remove the grenade cooking.

**Comment by TheFrenchGhosty** [comment]
Done in update 6.
