### ISSUE TITLE
Server name gets the "|" removed when round change

### ISSUE THREAD

**Issue by TheFrenchGhosty** [PussTheCat-org/PussTheCat.org-Cod4x-KTK#53]
The server name include the symbol `|` it works great when starting the server, works great when the server edits the server name to add the current round (if it's the first one)/current event.

However when editing the server name to add Round 2 (or Round 3 or Round 4) it will just remove the `|` symbol from it.

**Comment by VikingKampfsau** [comment]
Can you make an example?

**Comment by TheFrenchGhosty** [comment]
Round 1:

![1](https://user-images.githubusercontent.com/47571719/115714100-484e1300-a366-11eb-9e73-cf4274abccf3.png)

Round 2 (and later):

![2](https://user-images.githubusercontent.com/47571719/115714122-4dab5d80-a366-11eb-8043-c0ab0cc135be.png)

**Comment by VikingKampfsau** [comment]
Fix confirmed
