### ISSUE TITLE
Admin menu: can't select players on the left column

### ISSUE THREAD

**Issue by TheFrenchGhosty** [PussTheCat-org/PussTheCat.org-Cod4x-KTK#54]
In update 5 you made the player list on one page with multiples column, however, now, you can't select someone from the first column, it will just assume you're clicking on the second one.

**Comment by VikingKampfsau** [comment]
Ah crap, sounds like  the width of the buttons is to big (damn default cod4 menu buttons).
I have to create my own buttons then :/

**Comment by TheFrenchGhosty** [comment]
Fixed in update 6.
