### ISSUE TITLE
Zombie event: a green knife follow the guardians

### ISSUE THREAD

**Issue by TheFrenchGhosty** [PussTheCat-org/PussTheCat.org-Cod4x-KTK#55]
For whatever reason a green knife (I think it's the knife the assassins use) follow the guardians in the zombie event.

**Comment by VikingKampfsau** [comment]
Is the knife always following or does it happen when a zombie becomes guard?

**Comment by TheFrenchGhosty** [comment]
It seems to be always following, I think it follow the king too.

**Comment by TheFrenchGhosty** [comment]
Fixed in update 6.
