### ISSUE TITLE
Minplayers event/map rotation

### ISSUE THREAD

**Issue by VikingKampfsau** [PussTheCat-org/PussTheCat.org-Cod4x-KTK#56]
Thanks for the input.
I think it would be a nice addition to rotate the event (or map) when there are not enough players to start the round.
Like when you increase the minplayer setting in config, or when you the event is traitor but there are 2 players only.

**Comment by VikingKampfsau** [comment]
Added.

When no event is running then it grabs the wait time used for the reset of the events (scr_mod_minplayers_event_resettime) to tell the players to start votes.
Player can start votes when there are not enought players to start a round.

Possible votes: change map or change event.
Instructions are written in chat.

**Comment by TheFrenchGhosty** [comment]
Done in update 7.
