### ISSUE TITLE
RC heli is overpowered 

### ISSUE THREAD

**Issue by TheFrenchGhosty** [PussTheCat-org/PussTheCat.org-Cod4x-KTK#61]
The RC heli is REALLY overpowered, in my opinion it shouldn't be a different RCXD a a different Hardpoints completely.

The RC car is "okay" for 3 kills but compared to the heli it's just useless.

The RC heli should, in my opinion be its own hardpoints.

**Comment by VikingKampfsau** [comment]
Separated the killstreak, you now have to achieve different amount of kills to get rc car or rc heli, but you can not get both!
I think this way is fair.

**Comment by TheFrenchGhosty** [comment]
Done in update 7.
