### ISSUE TITLE
Crash: Server kicked everyone

### ISSUE THREAD

**Issue by TheFrenchGhosty** [PussTheCat-org/PussTheCat.org-Cod4x-KTK#68]
The server kicked everyone for no reason.

![crash](https://user-images.githubusercontent.com/47571719/115962043-e4b01b00-a508-11eb-8af3-b4b9ee2cb946.png)

Map was mp_creek, and we were at the last round.

The only thing in the server log that *might be* related:

Out of range reliableAcknowledge message from [MY NICKNAME] - reliableSequence is 14473, reliableAcknowledge is -1

**Comment by VikingKampfsau** [comment]
Looks like a cod4x bug to me - game failed to set the remaining round time (or the time played)
