### ISSUE TITLE
Server sometimes switch to a map without bots

### ISSUE THREAD

**Issue by TheFrenchGhosty** [PussTheCat-org/PussTheCat.org-Cod4x-KTK#69]
Related: #26

The server is supposed to switch to map that support bots, however, it did switch to a map without bots:

![rotation_bots](https://user-images.githubusercontent.com/47571719/115962143-7750ba00-a509-11eb-8c00-2e1e51628003.png)

**Comment by VikingKampfsau** [comment]
The empty rotation script just kicks in when the server is really empty, otherwise it does not switch the map.
The event will reset, i think that's all.

**Comment by TheFrenchGhosty** [comment]
@VikingKampfsau The server was really empty, I connected because it switch to this map.
