### ISSUE TITLE
mp_luna2: Crash - Sys_Error: Could not load default asset for asset type 'M E9'

### ISSUE THREAD

**Issue by TheFrenchGhosty** [PussTheCat-org/PussTheCat.org-Cod4x-KTK#73]
```
Unloading assets from fastfile 'mp_luna2' and creating default assets stubs

Sys_Error: Could not load default asset for asset type 'M E9'
```

Server crashed, looks like a typo to me.

Might be the mod or the map (the map used to work though so I don't know.

**Comment by TheFrenchGhosty** [comment]
Some users have reported that it might be related to the vote map.

Note that I'm running the latest update, so more testing is needed.

**Comment by TheFrenchGhosty** [comment]
Viking did some testing, the problem is when the server "leave" mp_luna2 to go to another map.

**Comment by VikingKampfsau** [comment]
Reported at cod4x forums.
Confirmed by other person, running a different mod that it happens for him as well.

https://cod4x.me/index.php?/forums/topic/5834-map-switch-from-mp_luna2-to-whatever/

So not related to ktk... closed
